Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"
  config.vm.hostname = "m8alma"
  config.vm.define "m8alma" do |d|
    d.vm.provider "virtualbox" do |vb|
      vb.name = "m8alma"
      vb.linked_clone = true
      (1..6).each do |n|
        disk_file = "./.vagrant/machines/disks/m8alma-disk-d#{n}.vdi"
        unless File.exists?(disk_file)
          vb.customize ['createmedium', 'disk', '--filename', disk_file, '--size', 500]
        end
        vb.customize ['storageattach', :id, '--storagectl',  'SATA Controller', '--port', n, '--device', 0, '--type', 'hdd', '--medium', disk_file ]
      end
    end
  end
end
